name: Project Board Automation

on:
  issues:
    types: [opened, assigned, closed]

jobs:
  automate-project:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue on project board
        uses: alex-page/github-project-automation-plus@v0.7.2
        with:
          project: Adonis Edge MVP
          column-open: To Do
          column-assigned: In Progress
          column-closed: Done
          repo-token: ${{ secrets.GITHUB_TOKEN }}
